### ISSUE TITLE
可以详细讲一下DrowsyNet的训练测试过程吗

### ISSUE THREAD

**Issue by MeeraBran** [shicheng123moon/DrowsyNet#1]
你好，请问可以详细写一下DrowsyNet的训练过程吗？或者给一下drowsyNet的源文件吗？我不太懂
我看您说DrowsyNet网络模型时说用的是tensorflow框架，后面给的百度网盘里的模型是caffe的，所以我有点不太懂
还有就是，您训练好的left_eye.caffemodel、right_eye.caffemodel以及mouth.caffemodel是三个不同的模型，怎么将它们整合到一起完成对疲劳的判断呢？

**Comment by shicheng123moon** [comment]
百度网盘里有drowsynet.rknn的模型，使用tensorflow pb模型转化的。Firefly RK3399Pro需要模型转换和量化。 Caffe模型是用来检测眼睛嘴巴张开闭合时用的，也可以不用。用阈值处理就OK

**Comment by shicheng123moon** [comment]
百度网盘里有drowsynet.rknn的模型，使用tensorflow pb模型转化的。Firefly RK3399Pro需要模型转换和量化。 Caffe模型是用来检测眼睛嘴巴张开闭合时用的，也可以不用。用阈值处理就OK
