### ISSUE TITLE
请问drowsynet.ipynb中的train_model函数中的权重模型weight_fn = "D:/TimeSeriesPrediction/DDD/lstm_fcn_model/drowsynet_weights.h5"在哪呀

### ISSUE THREAD

**Issue by MeeraBran** [shicheng123moon/DrowsyNet#2]
请问drowsynet.ipynb中的train_model函数中的权重模型weight_fn = "D:/TimeSeriesPrediction/DDD/lstm_fcn_model/drowsynet_weights.h5"在哪呀？我没有在你上传的文件中找到

**Comment by shicheng123moon** [comment]
自己训练一下，我开源这个代码主要是为对疲劳检测感兴趣的研究者提供方便，整套实时系统给您搭好了，里面的算法可以换成自己的，不限于3D卷积、2D卷积、单相片动作识别、表情识别等。
