### ISSUE TITLE
请问drowsynet.rnkk模型怎么转换成.pb模型的呀

### ISSUE THREAD

**Issue by MeeraBran** [shicheng123moon/DrowsyNet#3]
昨天您说了训练好的drowsynet模型是drowsynet.rnkk，但是我百度了一下，没有找到它是怎么转换成常见的.h5，.pb，.pth或者.caffemodel模型。您昨天说的是用TensorFlow pb模型转化的，可以提供一下源文件吗？

**Comment by shicheng123moon** [comment]
关于RKNN转模型，Firefly RK3399pro支持的框架覆盖tensorflow，Keras， Pytorch等。在他们提供的SDK里有转模型demo的PY文件。就几行代码，需要您研究一下。

**Comment by MeeraBran** [comment]
好的，谢谢
