### ISSUE TITLE
请问可以详细讲一下预处理数据这一块吗？

### ISSUE THREAD

**Issue by MeeraBran** [shicheng123moon/DrowsyNet#4]
1. 没有看懂您preprocessing文件夹中的create_train_images.py文件，create_train_drowsy_merge.py文件，create_train_attribute_csv.py文件分别是用来干什么的，依次类推测试集和验证集，我知道最后create_total_merge.py是将所有的csv文件整合到一起形成最终total_merged_drowsy.csv数据集的。
2. 这些文件的先后执行顺序是什么？
3. total_merged_drowsy.csv文件中的字段drowsiness, mouth, head, eye, part_0_x, part_0_y分别代表什么意思啊？drowsiness为1代表瞌睡，那么mouth和eye等于0又是什么意思呢?

**Comment by shicheng123moon** [comment]
星期一会把标签text文件补上。
