### ISSUE TITLE
请问drowsynet模型中的扩张LSTM体现在哪呀

### ISSUE THREAD

**Issue by MeeraBran** [shicheng123moon/DrowsyNet#5]
您好，我看了你的drowsynet代码，构建网络的时候只有一层keras提供的LSTM，没有看到三层的扩张的LSTM。看您的论文中说的是三层扩张的LSTM，不太懂，所以来问问您。

**Comment by MeeraBran** [comment]
def generate_drowsynet():   # 构建Drowsynet网络
    ip = ip = Input(shape=(seq_len, n_channels))

    x = LSTM(8)(ip)
    x = Dropout(0.8)(x)
就只有这一个LSTM，或者我哪里漏看了您的代码，真诚向您请教

**Comment by shicheng123moon** [comment]
看一下drowsynetv1.ipynb,  扩张卷积LSTM有实现。
