### ISSUE TITLE
请问您最后开发的系统中使用了DrowsyNet模型吗？具体在哪里体现呢？

### ISSUE THREAD

**Issue by MeeraBran** [shicheng123moon/DrowsyNet#6]
您好，我看您的md文档中说 “还采用了数据驱动的神经网络DrowsyNet方法”，可是我看开发系统中好像使用的是caffe模型？没有看到DrowsyNet多变量序列模型，因为我很想知道使用面部地标序列训练出来的模型如何应用。
我只看到了实时计算EAR，MAR，FOM，PERCLOS等指标，没有看到使用DrowsyNet模型预测出来的结果，或者我哪里漏看了，真诚向您请教。

**Comment by shicheng123moon** [comment]
看一下FaceAnalysisModel.cpp，最后的代码，你跑出来吗

**Comment by shicheng123moon** [comment]
有的，系统比较复杂，在Mainwindow UI里有这个输出

**Comment by shicheng123moon** [comment]
我没有用到caffe模型

**Comment by shicheng123moon** [comment]
系统的逻辑有点复杂，有很多集承，参数转来转去的。请您多包涵

**Comment by MeeraBran** [comment]
> 我没有用到caffe模型

我在文件里看到了CaffeClassifier.cpp这个文件，我以为您用到了caffe模型，不好意思

**Comment by shicheng123moon** [comment]
没事没事，Caffe模型，RK3399pro不支持，还是用的CPU哦，所有就没有用到
